services:
  exvpn-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: exvpn-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot/data:/app/bot/data
    networks:
      - exvpn-network

networks:
  exvpn-network:
    name: ${CENTRAL_API_NETWORK_NAME}
    external: true