services:
  exvpn-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: exvpn-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot/data:/app/bot/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - exvpn-network

  postgres:
    image: postgres:16-alpine
    container_name: exvpn-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - exvpn-network

volumes:
  postgres_data:

networks:
  exvpn-network:
    name: ${CENTRAL_API_NETWORK_NAME}
    external: true
