services:
  exvpn-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: exvpn-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot/data:/app/bot/data
    depends_on:
      - postgres
    # networks:
    #   - exvpn-network

  postgres:
    image: postgres:16-alpine
    container_name: exvpn-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - exvpn-network

volumes:
  postgres_data:

# networks:
#   exvpn-network:
#     name: ${CENTRAL_API_NETWORK_NAME}
#     external: true
